language: elixir
elixir:
  - 1.3.2
  - 1.4.2
otp_release:
  - 18.0
  - 19.0

before_install:
  - wget https://bitcoin.org/bin/bitcoin-core-0.14.0/bitcoin-0.14.0-x86_64-linux-gnu.tar.gz  && tar -xzvf bitcoin-0.14.0-x86_64-linux-gnu.tar.gz -C /home/travis

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  - mkdir -p /home/travis/.bitcoin && cp bitcoin.conf /home/travis/.bitcoin/bitcoin.conf
  - /home/travis/bitcoin-0.14.0/bin/bitcoind -regtest -daemon
script:
  - sleep 15
  - mix test
notifications:
  recipients:
    - kelostrada@gmail.com
